# Uncomment the following lines to enable the workflow
# version: 2
# updates:
# - package-ecosystem: bundler
#   directory: "/"
#   schedule:
#     interval: daily
#   open-pull-requests-limit: 10
# - package-ecosystem: github-actions
#   directory: "/"
#   schedule:
#     interval: daily
#   open-pull-requests-limit: 10
